# Generated by Django 5.1.3 on 2024-12-13 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, verbose_name='사용자 아이디')),
                ('user_nm', models.CharField(max_length=40, verbose_name='사용자명')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
            ],
        ),
    ]
