# Generated by Django 5.1.3 on 2025-01-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stat',
            field=models.PositiveSmallIntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=1),
        ),
    ]
