# Generated by Django 5.1.3 on 2024-12-13 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achv_name', models.CharField(max_length=100, verbose_name='목표명')),
                ('achv_max_value', models.PositiveIntegerField(default=0, verbose_name='목표값')),
                ('achv_value', models.PositiveIntegerField(default=0, verbose_name='현재값')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('user_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='사용자키')),
            ],
        ),
    ]
