# Generated by Django 5.1.3 on 2024-12-09 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('user_nm', models.CharField(max_length=40)),
                ('create_dt', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achv_name', models.CharField(max_length=100)),
                ('achv_max_value', models.PositiveIntegerField(default=0)),
                ('achv_value', models.PositiveIntegerField(default=0)),
                ('create_dt', models.DateTimeField(verbose_name='date published')),
                ('update_dt', models.DateTimeField(verbose_name='date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
